### ISSUE TITLE
Implementar endpoint para recuperar opções de cobrança de mensalidades

### ISSUE THREAD

**Issue by alexandredsa** [sabrinarlima/macumbese-api#10]
`Apenas disponível para Admin`

#### Request

`Headers`

- Authorization Token: "1c39c8f1-f63d-4ab4-ae22-3f042614cebd"

#### Response

- Status: `200`

```json
{
    "value": 40
}
```

### ToDo
- [x] Criar tabela "billing_settings" (id, value)
- [x] Implementar método em BillingModel para alteração de valor
- [x] Criar nova controller - billing
- [x] Implementar rota GET - `/billings/settings` com acesso apenas para usuários 'ADMIN'
